#!/bin/bash
# clone github repository want to work and authorizing token

# clone dir
DIR=~/Belgeler/github
if [ ! -d $DIR ]; then
  mkdir -p $DIR
fi

# github user name
# paste güthub token --> token=
# github repositories
repo="
installarch
installarchde
"

pars() {
  git clone https://github.com/$user/$sel.git $DIR/$sel
  read -rep "Do you want to authorize $user/$sel with github token key ? (y,n) : " auth
  if [[ $auth =~ ^[yY]$ ]]; then
    cd $DIR/$sel
    git remote set-url origin https://$user:$token@github.com/$user/$sel.git
  fi
}

echo "Defined folder : $DIR"
read -rep "Do you want to clone all repos to defined folder? (y,n)" clonerepos
read -rep "Enter your github user name : " user
read -rep "Enter token key : " token
if [[ $clonerepos =~ ^[Yy]$ ]]; then
  for sel in $repo; do
    if [ ! -d $DIR/$sel ]; then
      pars
    else
      read -rep "$sel directory exist do you want to delete? (y,n) " confirm
      if [[ $confirm =~ ^[Yy]$ ]]; then
        rm -r $DIR/$sel
      else
        echo "$sel didn't deleted ... \n"
      fi
    fi
  done
fi

# nvim clone to .config and authorized
read -rep "Do you want to install neovim dotfiles (y,n) " nvm
if [[ $nvm =~ ^[Yy]$ ]]; then
  git clone https://github.com/$user/nvim.git ~/.config/nvim
  cd ~/.config/nvim
  git remote set-url origin https://$user:$token@github.com/$user/nvim.git
fi
