#!/bin/bash

message="Açık pencere yok!"

windows() {
  hyprctl clients -j | jq 'map("\(.address) | \(.workspace.id) | \(.title) --> \(.class)")' | jq -r ".[]"
}
rofiwindows() {
  windows | rofi -dmenu -theme $HOME/.config/rofi/window.rasi -matching normal -i
}

window=$(hyprctl clients)
if [ "$window" = "unknown request" ]; then
  notify-send "$message"
  exit 0
else
  address=$(rofiwindows | cut -d "|" -f 1)
  echo $address
  hyprctl dispatch focuswindow address:$address
fi
