#!/bin/bash

get_info() {
  brightnessctl -m | cut -d "," -f 4
}

get_current() {
  current=$(get_info | sed 's/%//')
}

notify_user() {
  notify-send -e -h string:x-canonical-private-synchronous:info -h int:value:$current -u low "Ekran Parklalığı: $current%"
}

change_backlight() {
  brightnessctl set "$1" && get_current && notify_user
}

case "$1" in
"up")
  change_backlight "10%+"
  ;;
"down")
  change_backlight "10%-"
  ;;
*)
  get_info
  ;;
esac
