#!/bin/bash

SERVICE="hypridle"
if [[ "$1" == "status" ]]; then
    sleep 1
    if pgrep -x "$SERVICE" >/dev/null ;then
        echo '{"text": "RUNNING", "class": "activated", "tooltip": "Ekran kilidi devrede"}'
    else
        echo '{"text": "NOT RUNNING", "class": "deactivated", "tooltip": "Ekran kilidi devredışı"}'
    fi
fi
if [[ "$1" == "toggle" ]]; then
    if pgrep -x "$SERVICE" >/dev/null ;then
        killall hypridle
    else
        hypridle
    fi
fi
