#!/bin/bash

DIR=$HOME/Resimler/Wallpaper/
PICS=($(find ${DIR} -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" -o -name "*.gif" \)))

RANDOMPICS=${PICS[$RANDOM % ${#PICS[@]}]}

if [[ $(pidof swaybg) ]]; then
  pkill swaybg
fi

swww query || swww init

#change-wallpaper using swww
#swww img ${DIR}/${RANDOMPICS} --transition-fps 30 --transition-type any --transition-duration 3
swww img ${RANDOMPICS} --transition-fps 30 --transition-type any --transition-duration 3
